### PR TITLE
Suppress UI elements when there is an error in retrieving masterfiles

### LINKED ISSUE #47: When there's an error retrieving the Master File, suppress UI elements
### Description
When / if there's an error retrieving a master file (either via network error, or wrong id typed into the browser url window), we should suppress any UI elements indicating the user can do something.

ui-elements-visible-on-error

### Done Looks Like
- When there's an error retrieving a master file, the user sees an error message.
- And all UI elements indicating a user action is allowed, are hidden.

### To Do
- [x] Re-evaluate message display and content.
- [x] Apply some type of global error Redux property which can be used to measure whether the master file was not retrieved.

### PR DESCRIPTION
**Pull request by Dananji**
Fixes #47 
This PR includes refactoring `show-forms` and its parameter `disabled` throughout the code.

### CODE REVIEW

File: src/reducers/forms.js [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+      if (action.code === 0) {
+        return Object.assign({}, state, {
+          editingDisabled: true
+        });
+      }
+
+      return Object.assign({}, state, {
+        editingDisabled: false
+      });
+
```
Comment (adamjarling) [inline src/reducers/forms.js]: Might need a `break` in this case block?

Comment (Dananji) [reply src/reducers/forms.js]: Yeah, when I add a `break` there, it gives a warning in the console, `Line 21:  Unreachable code  no-unreachable`. Maybe because, we have a default `return` statement for that case? And according to the internet this comes from `ESLint` configuration, which I have in my VSCode?

When I remove the `break` statements for the other 2 cases, I got a warning in the console, `Expected a 'break' statement before 'case'  no-fallthrough`, but for this I don't get that.

Comment (adamjarling) [reply src/reducers/forms.js]: Ah, true because it returns before hitting the `break`.    I think it's complaining about the other 2 scenarios with if there was no `break` as the return may never hit.   Never mind, looks good!
