### PR TITLE
Error boundary implementation for Peaks waveform component rendering

### LINKED ISSUE #31: Wrap external network communication components in an error boundary component
### Description
When network issues pop up accessing external JSON data, the app should not completely fail.  Need to wrap in a React error boundary to handle gracefully.

### Done Looks Like
- On network data errors, the app fails gracefully and provides a reasonable error message to the user.

### Tasks
- [ ] Create an error boundary component for network communication
- [ ] Wrap existing network communications
- [ ] Handle error messaging display to user

### PR DESCRIPTION
**Pull request by adamjarling**
fixes #31 

This PR wraps any component rendering errors in a React error boundary.   Error boundaries aren't used typically for async network requests, or event handling.... so limited scope of this pattern to just component rendering errors.

### CODE REVIEW

File: src/components/WaveformErrorBoundary.js [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+  }
+
+  state = {
+    showAlert: false
+  };
+
+  static getDerivedStateFromError(error) {
+    // Update state so the next render will show the fallback UI.
+    return { hasError: true, showAlert: true };
+  }
```
Comment (Dananji) [inline src/components/WaveformErrorBoundary.js]: @adamjarling This is awesome! :+1: I didn't know this existed.
But it doesn't hit this part of the code after the Waveform network request returns an error.

File: src/components/WaveformErrorBoundary.js [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+
+  handleDismiss = () => {
+    this.setState({ showAlert: false });
+  };
+
+  render() {
+    if (this.state.hasError && this.state.showAlert) {
+      return (
```
Comment (Dananji) [inline src/components/WaveformErrorBoundary.js]: @adamjarling Here `this.state.showAlert` comes up undefined when I run this.

File: src/components/WaveformErrorBoundary.js (hunk 1 above)
Comment (adamjarling) [reply src/components/WaveformErrorBoundary.js]: Yea, something is off on this.  I noticed I had 2 branches locally for this:)   Will tidy up and re-push today.

Comment (adamjarling) [reply src/components/WaveformErrorBoundary.js]: In general looks like React's Error Boundaries are used for `render()` errors, and not for event handling or async network communication.  However if our network request code is returning some type of error object, maybe that'd trigger it?  I'll play a bit more with this.

File: src/components/WaveformErrorBoundary.js (hunk 2 above)
Comment (adamjarling) [reply src/components/WaveformErrorBoundary.js]: Ok, this is fixed up now.

File: src/components/WaveformErrorBoundary.js (hunk 1 above)
Comment (adamjarling) [reply src/components/WaveformErrorBoundary.js]: Ok, so re-reading your comment from above about this PR not handling the network request error, you're correct.  This particular error boundary handles any other errors which might occur  only in the `Waveform.js` component, during user interaction with the editor.  ie:
```
<WaveformErrorBoundary>
          <Waveform
            waveformRef={ref => (this.waveformContainer = ref)}
            mediaPlayerRef={ref => (this.mediaPlayer = ref)}
          />
</WaveformErrorBoundary>
```

The network request itself lives in `WaveformContainer.js`, and seems to be handled ok by the `try {} catch(e) {}` block?

Comment (Dananji) [reply src/components/WaveformErrorBoundary.js]: Oh okay :+1: Yeah the network request errors go through `handleResponse()` method, which triggers alerts from `AlertDismissable` component.
