### PR TITLE
Fix adding segments at the end of the waveform

### LINKED ISSUE #54: Alert for saving structure show up for inline form save button click
### Description

If structure is edited after saving it to back-end server once, the alert for saving the structure shows up whenever save button is clicked on inline forms.

### Done Looks Like

The alert does not show when save buttons in inline forms are clicked

### LINKED ISSUE #56: Adding a new segment at the end of the waveform
### Description

In a scenario where, there is a segment, with its end time equal to the end time of the media file in the waveform, and when;

- the playhead is placed at the start of that last segment. And the `Add a Timespan` button is clicked, the application crashes, with the error; `RangeError: peaks.segments.add(): endTime should be greater than startTime`
- the playhead is placed within the last segment. And the `Add a Timespan` button is clicked, the application adds a segment starting from the end time of the media file.

### Done Looks Like

The application should not add any segments after the end time of the media file.

### PR DESCRIPTION
**Pull request by Dananji**
fixes #56
fixes #54 

To clear the `alertObj` in each parent component a function is defined to clear its state. And this function is then invoked within the `AlertContainer` when closing the alert. This clears up the object for the alert and fixes the bug in #54.

### CODE REVIEW

File: src/services/alert-status.js [hunk 1]
```diff
@@ -6,13 +6,16 @@ export const FETCH_STRUCTURED_DATA_ERROR =
...
 
 /**
  * Helper function which prepares a configuration object to feed the AlertContainer component
  * @param {number} status Code for response
+ * @param {function} clearAlert A function defined in the hosting component to clear the alert object in component's state
  */
-export function configureAlert(status) {
-  let alertObj = { alertStyle: 'danger' };
+export function configureAlert(status, clearAlert) {
+  let alertObj = { alertStyle: 'danger', clearAlert: clearAlert };
```
Comment (adamjarling) [inline src/services/alert-status.js]: Another tiny ES6/7 trick... when the property name is equal to a variable of same name, you could just do 

`{ alertStyle: 'danger', clearAlert }`

File: src/containers/AlertContainer.js [hunk 2]
```diff
@@ -23,9 +25,15 @@ class AlertContainer extends Component {
...
   }
+  componentWillReceiveProps(nextProps) {
+    if (isEmpty(nextProps)) {
+      this.setState({ show: false });
+    }
+  }
 
   handleDismiss = () => {
     this.setState({ show: false });
+    this.props.clearAlert();
```
Comment (adamjarling) [inline src/containers/AlertContainer.js]: I like this callback solution.  Nice work.

File: src/services/alert-status.js (hunk 1 above)
Comment (Dananji) [reply src/services/alert-status.js]: Oh cool! Did not know that. Will keep that in mind for next time :)

Comment (Dananji) [reply src/services/alert-status.js]: @adamjarling Or should I fix it now?

File: src/containers/AlertContainer.js (hunk 2 above)
Comment (Dananji) [reply src/containers/AlertContainer.js]: @adamjarling Do you think there is a way improve this further more? Anytime we create `AlertContainer` we need to create that `clearAlert()` function. Anyway to avoid that?

Comment (adamjarling) [reply src/containers/AlertContainer.js]: I'm not entirely sure.  I guess it depends on whether we want to the `<AlertContainer />` to handle the logic for hiding/showing itself, or whether we want to wrap `<AlertContainer />` in a conditional block, in its parent component?

The tricky part I found, was combining the dismissible part, within `AlertContainer`.

What seems to make the most sense to you?

File: src/services/alert-status.js (hunk 1 above)
Comment (adamjarling) [reply src/services/alert-status.js]: Next time is fine.

File: src/containers/AlertContainer.js (hunk 2 above)
Comment (adamjarling) [reply src/containers/AlertContainer.js]: Or should the logic to clear out a component's errorObject which feeds the `AlertContainer`, live within the calling component?   I could see this go many ways.

Comment (Dananji) [reply src/containers/AlertContainer.js]: I think one of the main purposes of breaking Alerts out of redux-store into a separate React component was to give it the full control of the Alert. So keeping the hiding/showing logic within the `AlertContainer` is best. Keeping clearing the `alertObj` within the calling component and passing it as a `prop` into `AlertContainer` works best for now.

And keeping `<AlertContainer />` within a conditional block, what could we use as a condition in here? Because the `alertObj` resides within the hosting component, which does not get updated when we dismiss the alert from within the `AlertContainer`.

> Or should the logic to clear out a component's errorObject which feeds the `AlertContainer`, live within the calling component? I could see this go many ways.

This is what is done in this PR?

Comment (adamjarling) [reply src/containers/AlertContainer.js]: Yea, I think the way it's set up now, in this PR seems to work.  Let's run with this for now.   Feel free to merge this one in.
