### PR TITLE
Fix bug - allowing only one action to change structure at a given time

### LINKED ISSUE #55: Bugs in editing timespans
### Description

- If an existing timespan is selected for editing while adding a new timespan, an error is thrown.
- If an existing timespan is deleted while adding a new timespan, the Timespan form values show as `NaN:NaN:NaN`

related to #42

### Done Looks Like
- Only one list Item may be edited (or confirm deleted) at a time.
- All non-currently edited list items should have their controls set to disabled.

### PR DESCRIPTION
**Pull request by Dananji**
Fixes #55

### CODE REVIEW

File: src/components/ButtonSection.js [hunk 1]
```diff
@@ -125,12 +151,14 @@ export { ButtonSection as PureButtonSection };
 
 const mapStateToProps = state => ({
   smData: state.smData,
-  peaksInstance: state.peaksInstance
+  peaksInstance: state.peaksInstance,
+  showForms: state.showForms
```
Comment (adamjarling) [inline src/components/ButtonSection.js]: I think at some point we refactor the naming convention on this Redux reducer `show-forms`.  It's become a catch-all and last few times I see it referenced it's confusing to what it actually does.  

Maybe the reducer and action is renamed to something like `forms`, and `disabled` gets more specific to what is disabled?

Comment (Dananji) [reply src/components/ButtonSection.js]: Yeah, sounds like a good idea. It's kind of vague now, and someone new will be confused. I'll refactor these in the ticket I'm working now.
